var subject = require('./subject.js');
var mock = require('mock-fs');
subject.inc(4,undefined);
subject.inc(4,"Salt");
subject.inc(-4,undefined);
subject.inc(-4,"Salt");
subject.weird(8,3,51,"strict");
subject.weird(8,3,51,"werw");
subject.weird(8,3,51,"strictSalt");
subject.weird(8,3,51,"");
subject.weird(8,3,33,"strict");
subject.weird(8,3,33,"werw");
subject.weird(8,3,33,"strictSalt");
subject.weird(8,3,33,"");
subject.weird(8,-1,51,"strict");
subject.weird(8,-1,51,"werw");
subject.weird(8,-1,51,"strictSalt");
subject.weird(8,-1,51,"");
subject.weird(8,-1,33,"strict");
subject.weird(8,-1,33,"werw");
subject.weird(8,-1,33,"strictSalt");
subject.weird(8,-1,33,"");
subject.weird(6,3,51,"strict");
subject.weird(6,3,51,"werw");
subject.weird(6,3,51,"strictSalt");
subject.weird(6,3,51,"");
subject.weird(6,3,33,"strict");
subject.weird(6,3,33,"werw");
subject.weird(6,3,33,"strictSalt");
subject.weird(6,3,33,"");
subject.weird(6,-1,51,"strict");
subject.weird(6,-1,51,"werw");
subject.weird(6,-1,51,"strictSalt");
subject.weird(6,-1,51,"");
subject.weird(6,-1,33,"strict");
subject.weird(6,-1,33,"werw");
subject.weird(6,-1,33,"strictSalt");
subject.weird(6,-1,33,"");
mock({"path/fileExists":{},"pathWithContent":{"file1":"text content"},"pathWithoutContent":{"file1":""},"dirWithContent":{"file1":""},"dirWithoutContent":{}});
	subject.fileTest('dirWithContent','pathWithContent/file1');
	subject.fileTest('dirWithContent','path/fileNotExists');
	subject.fileTest('dirWithContent','pathWithoutContent/file1');
	subject.fileTest('path/fileNotExists','pathWithContent/file1');
	subject.fileTest('path/fileNotExists','path/fileNotExists');
	subject.fileTest('path/fileNotExists','pathWithoutContent/file1');
	subject.fileTest('dirWithoutContent','pathWithContent/file1');
	subject.fileTest('dirWithoutContent','path/fileNotExists');
	subject.fileTest('dirWithoutContent','pathWithoutContent/file1');
mock.restore();
subject.normalize("066-468-0063");
subject.format("835-774-1156","###-###-#### x#####",true);
subject.format("835-774-1156","###-###-#### x#####",{normalize:true});
subject.format("835-774-1156","###-###-#### x#####",false);
subject.format("835-774-1156","###-###-#### x#####",{normalize:false});
subject.blackListNumber("212-479-6936");
subject.blackListNumber("");
